service:
  name: adminpanel-qc-quality-control

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  vpc:
    securityGroupIds: ${file(./resources/environment/${self:provider.stage}.yml):securitygroupids}
    subnetIds: ${file(./resources/environment/${self:provider.stage}.yml):subnetids}
    role: ${file(./resources/environment/${self:provider.stage}.yml):iamrole}
  logRetentionInDays: 14
  
  environment:
    APPLICATION_NAME: ${self:service.name}
    NODE_ENV: ${self:provider.stage}
    REGION: ${opt:region, self:provider.region}
    VAULT_URL: ${file(./resources/environment/${self:provider.stage}.yml):vault.vaultUrl}
    VAULT_PATH: ${file(./resources/environment/${self:provider.stage}.yml):vault.vaultPath}
    VAULT_SSM_PATH: ${file(./resources/environment/${self:provider.stage}.yml):vault.vaultSsmPath}
    VAULT_TOKEN: ${file(./resources/environment/${self:provider.stage}.yml):vault.vaultToken}
    DB_HOST: ${file(./resources/environment/${self:provider.stage}.yml):database.host}
    DB_PORT: ${file(./resources/environment/${self:provider.stage}.yml):database.port}
    DB_NAME: ${file(./resources/environment/${self:provider.stage}.yml):database.schema}
    DB_USERNAME: ${file(./resources/environment/${self:provider.stage}.yml):database.username}
    RECORDS_PER_CHUNK: ${file(./resources/environment/${self:provider.stage}.yml):recordsPerChunk}
    
functions:
  qcQualityControl:
    handler: src/main.QCHistory
    timeout: 900
    events: 
      - schedule: cron(0 17 * * ? *)
