env: "local"

iamrole: arn:aws:iam::821716379579:role/rbh-dev-adminpanel-qc-quality-control-batch-serverlesss-role

securitygroupids:
  - sg-0d0171e1cebedbd1d

subnetids:
  - subnet-0acb58801f44686a7
  - subnet-0a8503ff608639fab
  - subnet-00c6f57c3d0af1459

vault:
  vaultUrl: http://vault-cluster.rbhdev.internal:8200
  vaultPath: /secret/data/robinhood/adminpanel-qc-quality-control-batch-serverlesss/dev
  vaultSsmPath: rbh-dev
  vaultToken: ${ssm:/rbh-dev/VAULT_TOKEN~true}

database:
  host: "rbh-dev-aurora-db.rbhdev.internal"
  port: "3306"
  schema: "adminpanel"
  username: "rbh_lambda"
